### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by johnblommers** [mawise/bookshelf#5]
Upon installing all the  bits:

```
ruby app.rb "~/Calibre Library/"
/home/johnb/gems/gems/sqlite3-2.0.3/lib/sqlite3/database.rb:121:in `open_v2': unable to open database file (SQLite3::CantOpenException)
	from /home/johnb/gems/gems/sqlite3-2.0.3/lib/sqlite3/database.rb:121:in `initialize'
	from /home/johnb/Applications/bookshelf/calibre.rb:7:in `new'
	from /home/johnb/Applications/bookshelf/calibre.rb:7:in `connect'
	from app.rb:7:in `<main>'
```

**Comment by mawise** [comment]
Sounds like it might be a file permissions issue.  You could make sure the user account that runs the bookshelf has read permissions on the Calibre Library.
